### ISSUE TITLE
Source Format Problem Reports

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#15]
## Story

As a _creator|user|admin_ I want to see if there are structural or formatting issues with my content so that I can fix them.

## Notes

The underlying architecture for reporting this information has been completed.  What is needed to complete this task is the following:

* For Markdown Source texts, report the following:
  * [ ] Run a markdown linter against the source files, (perhaps something like `mdl`, https://github.com/unfoldingWord-dev/door43.org/blob/develop/cibuild.sh#L5).  Report output.
* For OBS projects:
  * [ ] Report missing chapters
  * [ ] Report missing frames
  * [ ] Report missing references
  * [ ] Report missing titles
  * [ ] Report missing or not translated front / back matter
* For USFM projects:
  * [ ] Report ill-formed USFM according to the spec.  This should include *at least* the information listed https://git.door43.org/Door43/ContentTechs/wiki/Minimum%20USFM%20Requirements#required .  Ideally, this information can be gleaned from USFM-Tools or perhaps another processor that already provides this.
  * [ ] Report missing chapters in book
  * [ ] Report missing verses in chapters
  * [ ] Report missing or untranslated book titles

See https://github.com/unfoldingWord-dev/uw-api/blob/develop/static/versification/ufw/ufw.vrs for a full list of the typical English versification system.

---

### Historical Notes From Initial Issue Creation

Related to #6, every repo in Gogs should have a build status indication. This should be keyed off of the output from the last time the conversion API tried to generate that repo.

This could be shown as a badge like a Travis CI badge.  The extended error information should also show up in the HTML page that is built ( #58 ).

For Markdown repos this should include:
- any ill-formed Markdown (perhaps run it through `mdl`, like we do in https://github.com/unfoldingWord-dev/door43.org/blob/develop/cibuild.sh#L5).
- Any ill-formed structure based on the resource type (OBS, tA, etc.)

For Scripture/USFM repos this should include:
- any ill-formed USFM according to the Spec
- any missing chapters or verses for a given book

Up for discussion on how this should be recorded.  I'm leaning toward saving this data in a JSON file for each commit in the S3 bucket (e.g. /u/[user]/[repo]/[short_commit_hash]/build_errors.json) and then have the project page ( #58 ) pull in this JSON file and display it nicely.

The badges are recorded in #213 .
Future task would be to tag repos that do not conform to the forthcoming resource container spec ( #79 ).
