### ISSUE TITLE
Apply Best Test & Code Practices to tx-sample client

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#156]
Required:
- [ ] Follow and revise if needed Phil's example in slack-lambda function
- [ ] Follow and revise if needed Phil's docs in the slack-lambda repo
- [ ] Move the documentation in the wiki on door43.org repo
  1
- [ ] Follow and revise if needed Phil's example for development best practices
- [ ] Move into wiki on door43.org repo
  1
- [ ] Write unit tests for tx-sample client sufficient for 70% code coverage
  3
- [ ] Travis CI is running the tests
  1
- [ ] Coveralls reporting code coverage
  1
