### ISSUE TITLE
Integration Testing for tX

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#407]
## Story

As a *developer* I want to have integration tests pass before deployment so that I don't have to worry about failures after deployment.

## DoD

~~* [ ] Setup (separate) integration environment in AWS~~
* [x] Tests to be run:
  * [x] OBS to HTML conversion
  * [x] USFM/Bible to HTML conversion

**Comment by richmahn** [comment]
Runs when merged into develop or master and checks against that environment.
