### ISSUE TITLE
Deploy develop to production

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#509]
## Story

As a *user* I want to see the latest updates on the live site so that I can use the new killer features.

## Notes

* [ ] Merge `develop` into `master` for tx-manager
* [ ] Merge `develop` into `master` for tx-manager-lambda
* [ ] Verify Travis CI deploys to AWS prod
* [ ] Update API gateway to account for new lambda functions
* [ ] Test output on production pipeline after release
