### ISSUE TITLE
Finish Project Pages

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#58]
## Story

As a _translator_ I want an easy to use project page so that I can see my rendered HTML content and get downloadable formats.
## Notes

We need to get a page layout setup for what would appear at door43.org/u/user/project/index.html.  The theme should match door43.org but the page layout needs to be created.  Important features that need included:
- [x] Get PDF Button ( #13 )
- [x] Get DOCX Button ( #14 )
- [x] Get ePub Button ( #57 )
- [x] HTML output for the resource
- [x] Simple navigation to get to previous builds 
- [x] Location for build errors to be reported ( #15 )

Possibly the top 3 bullets could actually just be a big "Download" button which offers a drop down where the user can select what file type they want (we have something similar for the audio/video downloads for OBS on https://unfoldingword.org/en/).
## Specs

URL Structure:
- [ ] Main page for project: /u/user_name/project_name/ (link to latest revision)
- [ ] Revision page for each project: /u/user_name/project_name/short_git_hash/  (let's use Gog's 10 digit short commit hash)
## Definition of Done
- [ ] Code is written to match screens below
- [ ] Travis CI is configured and passing:
  - [ ] For code building
  - [ ] For code unit testing
  - [ ] For deploying
- [ ] Coveralls is configured to report code test coverage (and is greater %70)
- [ ] Peer review of code before deploying to production
- [ ] Documentation of code functions (input/output, internal logic)
- [ ] Documentation of public facing features on Wiki as needed

**Comment by Thajny** [comment]
![artboard 3 copy 3](https://cloud.githubusercontent.com/assets/21183377/17873858/a3160f40-688d-11e6-971d-560274887f2e.jpg)
![starred projects](https://cloud.githubusercontent.com/assets/21183377/17873859/a324ca1c-688d-11e6-83dd-c75ba49345bc.jpg)

**Comment by Thajny** [comment]
![screen shot 2016-08-23 at 5 30 26 pm](https://cloud.githubusercontent.com/assets/21183377/17912229/eb969832-6957-11e6-97cd-e70b61f315a9.png)
![screen shot 2016-08-23 at 5 35 37 pm](https://cloud.githubusercontent.com/assets/21183377/17912246/0c46c43a-6958-11e6-8688-2d281ba5601c.png)
![screen shot 2016-08-23 at 5 31 12 pm](https://cloud.githubusercontent.com/assets/21183377/17912248/101bbd54-6958-11e6-875a-e817500566da.png)
![screen shot 2016-08-23 at 5 04 19 pm](https://cloud.githubusercontent.com/assets/21183377/17912251/13fe1098-6958-11e6-8c6b-6a2eb0b98d62.png)

**Comment by richmahn** [comment]
Where does the circle with the X come from? I don't see it in Font Awesome, only the black circle with an X.
