### ISSUE TITLE
Move DokuWiki Site to S3 + Cloudfront

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#770]
## Task

We would like to move the dw.door43.org site to be a static site served from S3 + Cloudfront.  The site is already in read only mode and making this move would mean one less server we have to maintain and would of course reduce the security risks.

## Notes

Similar to #704.

There is a site export admin plugin that we should attempt to use, https://github.com/i-net-software/dokuwiki-plugin-siteexport .

Checklist:

* [X] Setup s3 bucket
* [ ] Setup cloudfront on top of s3 bucket
* [ ] Use export function of DW to get a local copy of the site
* [ ] Upload site to s3 bucket
* [ ] Test links to verify they are all the same
* [ ] Update DNS for dw site to go to cloudfront instance

Something like the following can be used to upload the site to S3:

```
s3cmd -c your_config_file -M -F \
    --no-mime-magic \
    --add-header="Cache-Control:max-age=3600" \
    /local/src/dir s3://dw.door43.org/
```

The import parts for the S3 sync are the following:

* Do not use reduced redundancy
* Use the `-M` flag
* Cache-Control header is essential for Cloudfront to work like we want

**Comment by jag3773** [comment]
We've decided not to go through with this after trying for a couple weeks.  The main complication is that there are millions of files and most apps have problems tracking all of them.  Alternate idea is to move this site to a small VM and let it live out its days in peace.  Closing this issue for now.

Thanks for your work on this @phillip-hopper .
